replies = [
    "You are amazing just the way you are! 💖",
    "Thank you for bringing so much positivity into the world! 🌟",
    "Your kindness is truly inspiring! 😊",
    "Keep shining, beautiful soul! ✨",
    "Your smile is contagious! 😄",
    "You make the world a better place just by being in it! 🌍",
    "Your positivity is infectious! Spread it far and wide! 🌈",
    "You are capable of achieving great things! 💪",
    "Your heart is as big as the universe! 🌌",
    "Never forget how amazing you are! 🌻",
    "Your kindness is like a ray of sunshine on a cloudy day! ☀️",
    "You bring out the best in everyone around you! 🌷",
    "Your laughter is music to the soul! 🎶",
    "The world needs more people like you! 🌺",
    "You are loved more than you know! ❤️",
    "Your happiness is important, never forget that! 🌸",
    "You have a heart of gold! 💛",
    "Your courage is an inspiration to us all! 🦋",
    "You are a blessing to everyone who knows you! 🌼",
    "Your generosity knows no bounds! 🌹",
    "You are stronger than you think! 🏋️‍♀️",
    "Your love lights up the world! 🌟",
    "Keep being your wonderful self! 🌟",
    "You are an amazing friend and an even better person! 💕",
    "Your positive energy is a gift to everyone you meet! 🎁",
    "You are doing an awesome job! 🎉",
    "Your creativity is out of this world! 🌠",
    "You make the world a brighter place! 💡",
    "Your smile lights up the room! 🌞",
    "You are an inspiration to everyone you meet! 🌈",
    "Thank you for spreading joy and positivity! 🌸",
    "Your presence is a gift to those around you! 🎁",
    "You make every day brighter! ☀️",
    "You have a beautiful soul! 🌟",
    "You are a light in this world! 🌞",
    "Your kindness touches everyone around you! 🌼",
    "Thank you for being you! 🌻",
    "You have an incredible spirit! 🌟",
    "You bring so much happiness to others! 🌈",
    "Your heart is full of love and light! 💖",
    "You inspire me every day! 🌟",
    "You are a true blessing! 🌹",
    "Your words bring comfort and joy! 🌷",
    "Thank you for your wonderful energy! 🌸",
    "You make the world a better place! 🌍",
    "You are a shining example of kindness! 🌞",
    "Your love and light radiate to all! ✨",
    "Thank you for being a beacon of positivity! 🌈",
    "Your smile is a treasure! 💖",
    "You're a star! Keep shining bright! 🌟",
    "Thank you for making my day with your visit! 🌸",
    "Your support means the world to me! 💕",
    "Thanks for stopping by and checking out our page! 😊",
    "Grateful to have you here! Thanks for the visit! 🙌",
    "Thanks for the love! Appreciate you checking us out! 💖",
    "Big thanks for visiting! Hope you enjoyed it! 🌟",
    "Your visit just made my day! Thank you! 😄",
    "Thanks for taking the time to check us out! 🙏",
    "We appreciate your support! Thanks for stopping by! 🌸",
    "Thanks for swinging by! Your presence is appreciated! 🌷",
    "So glad you could check us out! Thanks a bunch! 😊",
    "Thanks for the visit! Your support keeps us going! 💪",
    "Thanks for dropping in! We hope to see you again! 🌞",
    "Much gratitude for checking out our page! 🙌",
    "We appreciate every visit—thanks for stopping by! 🌟",
    "Thank you for your time and attention! 😊",
    "Thanks for the support! It means a lot! 💖",
    "Thank you for being here! Your visit brightened our day! ☀️",
    "We’re grateful for your visit! Thanks so much! 🌸",
    "Thank you for checking us out! Your support is everything! 🌟",
    "Thanks for stopping by—your visit made our day! 🌈",
]
